apiVersion: v1
kind: Namespace
metadata:
  name: kube-engine-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-engine-test-executor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner
  namespace: kube-engine-test-executor
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/log
      - secrets
      - services
      - configmaps
      - events
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: kube-engine-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner
  namespace: kube-engine-test-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner
subjects:
  - kind: ServiceAccount
    name: runner
    namespace: kube-engine-test
