apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runner-agent.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "runner-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runner-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runner-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /agent
            - "--server_url={{.Values.serverUrl}}"
            - "--engine={{.Values.engine}}"
            - "--concurrency={{.Values.concurrency}}"
            {{- if eq .Values.engine  "kube"}}
            - "--engine.kube.namespace={{.Values.kube.executorNamespace}}"
            - "--engine.kube.executor_image={{.Values.kube.executorImage}}"
            - "--engine.kube.executor_path={{.Values.kube.executorPath}}"
            {{- end}}
            {{- if eq "vm" .Values.engine}}
            - "--engine.vm.runtime_image={{.Values.vm.runtimeImage}}"
            - "--engine.vm.executor_path={{.Values.vm.executorPath}}"
            - "--engine.vm.namespace={{.Values.vm.executorNamespace}}"
            - "--engine.vm.volumes={{.Values.vm.volumes}}"
            - "--engine.vm.image_root={{.Values.vm.imageRoot}}"
            {{- end}}
            - "--label={{.Values.label}}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
