jobs:
  - name: job1
    label: kube
    runson:
      label: vm
      vm:
        image: debian-11.qcow2
    steps:
      - name: build
        workingdirectory: /root
        commands:
          - pwd
          - df -h
          - sudo sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
          - apt-get update && apt-get install -y git build-essential gdb
#          - gcore -h
          - export https_proxy=192.168.31.229:20171
          - git clone https://github.com/redis/redis.git
          - cd redis/src
          - make -j$(nproc)