// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cox96de/runner/api (interfaces: ServerClient)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	api "github.com/cox96de/runner/api"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockServerClient is a mock of ServerClient interface.
type MockServerClient struct {
	ctrl     *gomock.Controller
	recorder *MockServerClientMockRecorder
}

// MockServerClientMockRecorder is the mock recorder for MockServerClient.
type MockServerClientMockRecorder struct {
	mock *MockServerClient
}

// NewMockServerClient creates a new mock instance.
func NewMockServerClient(ctrl *gomock.Controller) *MockServerClient {
	mock := &MockServerClient{ctrl: ctrl}
	mock.recorder = &MockServerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerClient) EXPECT() *MockServerClientMockRecorder {
	return m.recorder
}

// CreatePipeline mocks base method.
func (m *MockServerClient) CreatePipeline(arg0 context.Context, arg1 *api.CreatePipelineRequest, arg2 ...grpc.CallOption) (*api.CreatePipelineResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePipeline", varargs...)
	ret0, _ := ret[0].(*api.CreatePipelineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipeline indicates an expected call of CreatePipeline.
func (mr *MockServerClientMockRecorder) CreatePipeline(arg0, arg1 interface{}, arg2 ...interface{}) *ServerClientCreatePipelineCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipeline", reflect.TypeOf((*MockServerClient)(nil).CreatePipeline), varargs...)
	return &ServerClientCreatePipelineCall{Call: call}
}

// ServerClientCreatePipelineCall wrap *gomock.Call
type ServerClientCreatePipelineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ServerClientCreatePipelineCall) Return(arg0 *api.CreatePipelineResponse, arg1 error) *ServerClientCreatePipelineCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ServerClientCreatePipelineCall) Do(f func(context.Context, *api.CreatePipelineRequest, ...grpc.CallOption) (*api.CreatePipelineResponse, error)) *ServerClientCreatePipelineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ServerClientCreatePipelineCall) DoAndReturn(f func(context.Context, *api.CreatePipelineRequest, ...grpc.CallOption) (*api.CreatePipelineResponse, error)) *ServerClientCreatePipelineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLogLines mocks base method.
func (m *MockServerClient) GetLogLines(arg0 context.Context, arg1 *api.GetLogLinesRequest, arg2 ...grpc.CallOption) (*api.GetLogLinesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLogLines", varargs...)
	ret0, _ := ret[0].(*api.GetLogLinesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogLines indicates an expected call of GetLogLines.
func (mr *MockServerClientMockRecorder) GetLogLines(arg0, arg1 interface{}, arg2 ...interface{}) *ServerClientGetLogLinesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogLines", reflect.TypeOf((*MockServerClient)(nil).GetLogLines), varargs...)
	return &ServerClientGetLogLinesCall{Call: call}
}

// ServerClientGetLogLinesCall wrap *gomock.Call
type ServerClientGetLogLinesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ServerClientGetLogLinesCall) Return(arg0 *api.GetLogLinesResponse, arg1 error) *ServerClientGetLogLinesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ServerClientGetLogLinesCall) Do(f func(context.Context, *api.GetLogLinesRequest, ...grpc.CallOption) (*api.GetLogLinesResponse, error)) *ServerClientGetLogLinesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ServerClientGetLogLinesCall) DoAndReturn(f func(context.Context, *api.GetLogLinesRequest, ...grpc.CallOption) (*api.GetLogLinesResponse, error)) *ServerClientGetLogLinesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RequestJob mocks base method.
func (m *MockServerClient) RequestJob(arg0 context.Context, arg1 *api.RequestJobRequest, arg2 ...grpc.CallOption) (*api.RequestJobResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestJob", varargs...)
	ret0, _ := ret[0].(*api.RequestJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestJob indicates an expected call of RequestJob.
func (mr *MockServerClientMockRecorder) RequestJob(arg0, arg1 interface{}, arg2 ...interface{}) *ServerClientRequestJobCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestJob", reflect.TypeOf((*MockServerClient)(nil).RequestJob), varargs...)
	return &ServerClientRequestJobCall{Call: call}
}

// ServerClientRequestJobCall wrap *gomock.Call
type ServerClientRequestJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ServerClientRequestJobCall) Return(arg0 *api.RequestJobResponse, arg1 error) *ServerClientRequestJobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ServerClientRequestJobCall) Do(f func(context.Context, *api.RequestJobRequest, ...grpc.CallOption) (*api.RequestJobResponse, error)) *ServerClientRequestJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ServerClientRequestJobCall) DoAndReturn(f func(context.Context, *api.RequestJobRequest, ...grpc.CallOption) (*api.RequestJobResponse, error)) *ServerClientRequestJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateJobExecution mocks base method.
func (m *MockServerClient) UpdateJobExecution(arg0 context.Context, arg1 *api.UpdateJobExecutionRequest, arg2 ...grpc.CallOption) (*api.UpdateJobExecutionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateJobExecution", varargs...)
	ret0, _ := ret[0].(*api.UpdateJobExecutionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJobExecution indicates an expected call of UpdateJobExecution.
func (mr *MockServerClientMockRecorder) UpdateJobExecution(arg0, arg1 interface{}, arg2 ...interface{}) *ServerClientUpdateJobExecutionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobExecution", reflect.TypeOf((*MockServerClient)(nil).UpdateJobExecution), varargs...)
	return &ServerClientUpdateJobExecutionCall{Call: call}
}

// ServerClientUpdateJobExecutionCall wrap *gomock.Call
type ServerClientUpdateJobExecutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ServerClientUpdateJobExecutionCall) Return(arg0 *api.UpdateJobExecutionResponse, arg1 error) *ServerClientUpdateJobExecutionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ServerClientUpdateJobExecutionCall) Do(f func(context.Context, *api.UpdateJobExecutionRequest, ...grpc.CallOption) (*api.UpdateJobExecutionResponse, error)) *ServerClientUpdateJobExecutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ServerClientUpdateJobExecutionCall) DoAndReturn(f func(context.Context, *api.UpdateJobExecutionRequest, ...grpc.CallOption) (*api.UpdateJobExecutionResponse, error)) *ServerClientUpdateJobExecutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStepExecution mocks base method.
func (m *MockServerClient) UpdateStepExecution(arg0 context.Context, arg1 *api.UpdateStepExecutionRequest, arg2 ...grpc.CallOption) (*api.UpdateStepExecutionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStepExecution", varargs...)
	ret0, _ := ret[0].(*api.UpdateStepExecutionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStepExecution indicates an expected call of UpdateStepExecution.
func (mr *MockServerClientMockRecorder) UpdateStepExecution(arg0, arg1 interface{}, arg2 ...interface{}) *ServerClientUpdateStepExecutionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStepExecution", reflect.TypeOf((*MockServerClient)(nil).UpdateStepExecution), varargs...)
	return &ServerClientUpdateStepExecutionCall{Call: call}
}

// ServerClientUpdateStepExecutionCall wrap *gomock.Call
type ServerClientUpdateStepExecutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ServerClientUpdateStepExecutionCall) Return(arg0 *api.UpdateStepExecutionResponse, arg1 error) *ServerClientUpdateStepExecutionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ServerClientUpdateStepExecutionCall) Do(f func(context.Context, *api.UpdateStepExecutionRequest, ...grpc.CallOption) (*api.UpdateStepExecutionResponse, error)) *ServerClientUpdateStepExecutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ServerClientUpdateStepExecutionCall) DoAndReturn(f func(context.Context, *api.UpdateStepExecutionRequest, ...grpc.CallOption) (*api.UpdateStepExecutionResponse, error)) *ServerClientUpdateStepExecutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UploadLogLines mocks base method.
func (m *MockServerClient) UploadLogLines(arg0 context.Context, arg1 *api.UpdateLogLinesRequest, arg2 ...grpc.CallOption) (*api.UpdateLogLinesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadLogLines", varargs...)
	ret0, _ := ret[0].(*api.UpdateLogLinesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadLogLines indicates an expected call of UploadLogLines.
func (mr *MockServerClientMockRecorder) UploadLogLines(arg0, arg1 interface{}, arg2 ...interface{}) *ServerClientUploadLogLinesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadLogLines", reflect.TypeOf((*MockServerClient)(nil).UploadLogLines), varargs...)
	return &ServerClientUploadLogLinesCall{Call: call}
}

// ServerClientUploadLogLinesCall wrap *gomock.Call
type ServerClientUploadLogLinesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *ServerClientUploadLogLinesCall) Return(arg0 *api.UpdateLogLinesResponse, arg1 error) *ServerClientUploadLogLinesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *ServerClientUploadLogLinesCall) Do(f func(context.Context, *api.UpdateLogLinesRequest, ...grpc.CallOption) (*api.UpdateLogLinesResponse, error)) *ServerClientUploadLogLinesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *ServerClientUploadLogLinesCall) DoAndReturn(f func(context.Context, *api.UpdateLogLinesRequest, ...grpc.CallOption) (*api.UpdateLogLinesResponse, error)) *ServerClientUploadLogLinesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
