# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: Format
        run: make format

      - name: Lint
        run: make lint

      - name: Check
        run: git diff --exit-code
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build ./...
      - name: Test
        run: go test -race -coverprofile cover.out -coverpkg=./... ./...

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions/
      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Test
        run: go test -tags kube_integration -race -coverprofile cover.out -coverpkg=./... ./engine/kube/...